name: elim
description: "Elim Trust Organization - Research, Healing, Resilience"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.3.0
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.0
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  http: ^1.5.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts will be added later when we have the font files
